In [4]:
import collections

class ListNode:
    def __init__(self, key, value):
        self.key = key
        self.val = value
        self.freq = 1
        
class LFUCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = dict() 
        self.usage = collections.defaultdict(collections.OrderedDict)
        self.LF = 0

    def get(self, key: int) -> int:
        if key not in self.cache:return -1
        node = self.cache[key]

        self.update(node, node.val)
        return node.val
        
    def put(self, key: int, value: int) -> None:
        if self.capacity == 0: return
        if key not in self.cache: 
            if len(self.cache) >= self.capacity:
                k, v = self.usage[self.LF].popitem(last=False)
                self.cache.pop(k)
            node = ListNode(key, value)
            self.cache[key] = node
            self.usage[1][key] = value
            self.LF = 1
        else: 
            node = self.cache[key]
            node.val = value
            self.update(node, value)
            
            
    def update(self, node, newVal):
        k, f = node.key, node.freq
        self.usage[f].pop(k)
        if not self.usage[f] and self.LF == f:
            self.LF += 1
        self.usage[f+1][k] = newVal
        node.freq += 1

lfu = LFUCache(2)
lfu.put(1, 1)       # cache=[1,_], cnt(1)=1
lfu.put(2, 2)       # cache=[2,1], cnt(2)=1, cnt(1)=1
print(lfu.get(1))   # return 1
                    # cache=[1,2], cnt(2)=1, cnt(1)=2
lfu.put(3, 3)       # 2 is the LFU key because cnt(2)=1 is the smallest, invalidate 2.
                    # cache=[3,1], cnt(3)=1, cnt(1)=2
print(lfu.get(2))   # return -1 (not found)
print(lfu.get(3))   # return 3
                    # cache=[3,1], cnt(3)=2, cnt(1)=2
lfu.put(4, 4)       # Both 1 and 3 have the same cnt, but 1 is LRU, invalidate 1.
                    # cache=[4,3], cnt(4)=1, cnt(3)=2
print(lfu.get(1))   # return -1 (not found)
print(lfu.get(3))   # return 3
                    # cache=[3,4], cnt(4)=1, cnt(3)=3
print(lfu.get(4))   # return 4
                    # cache=[4,3], cnt(4)=2, cnt(3)=3

1
-1
3
-1
3
4


In [5]:
class Node:
    def __init__(self, key, val):
        self.val = val
        self.key = key
        self.next = None
        self.prev = None
        
class LinkedList:
    def __init__(self):
        self.head = None
        self.tail = None
    
    def insert(self, node):
        if self.head is None:
            self.head = node
        else:
            self.tail.next = node
            node.prev = self.tail
        self.tail = node
            
    def delete(self, node):
        if node.prev:
            node.prev.next = node.next
        else:
            self.head = node.next
            
        if node.next:
            node.next.prev = node.prev
        else:
            self.tail = node.prev

class LRUCache:
    def __init__(self, capacity):
        self.list = LinkedList()
        self.dict = {}
        self.capacity = capacity
        
    def _insert(self, key, val):
        node = Node(key, val)
        self.list.insert(node)
        self.dict[key] = node

    def get(self, key):
        if key in self.dict:
            val = self.dict[key].val
            self.list.delete(self.dict[key])
            self._insert(key, val)
            return val
        return -1

    def put(self, key, val):
        if key in self.dict:
            self.list.delete(self.dict[key])
        elif len(self.dict) == self.capacity:
            del self.dict[self.list.head.key]
            self.list.delete(self.list.head)
        self._insert(key, val)

In [6]:
lRUCache = LRUCache(2)
lRUCache.put(1, 1)  # cache is {1=1}
lRUCache.put(2, 2)  # cache is {1=1, 2=2}
lRUCache.get(1)     # return 1
lRUCache.put(3, 3)  # LRU key was 2, evicts key 2, cache is {1=1, 3=3}
lRUCache.get(2)     # returns -1 (not found)
lRUCache.put(4, 4)  # LRU key was 1, evicts key 1, cache is {4=4, 3=3}
lRUCache.get(1)     # return -1 (not found)
lRUCache.get(3)     # return 3
lRUCache.get(4)     # return 4

4

In [5]:
import torch

x = torch.Tensor([0.6])
y = torch.Tensor([0.7])

x + y

tensor([1.3000])

In [6]:
x = 0.6
y = 0.7

x+y

1.2999999999999998

In [7]:
0.2 + 0.1

0.30000000000000004

In [10]:
import torch 

torch.manual_seed(0)
x = torch.rand((10,2))
x

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320],
        [0.3074, 0.6341],
        [0.4901, 0.8964],
        [0.4556, 0.6323],
        [0.3489, 0.4017],
        [0.0223, 0.1689],
        [0.2939, 0.5185],
        [0.6977, 0.8000],
        [0.1610, 0.2823]])

In [9]:
x.view(-1,4)

tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017],
        [0.0223, 0.1689, 0.2939, 0.5185],
        [0.6977, 0.8000, 0.1610, 0.2823]])